server:
  port: 8761

spring:
  ## Declare the default and active profiles
  profiles:
    default: dev
    active: dev
  ## Declare the Applicationn name
  application:
    name: ms-eureka-server
  ## Declare the ansi colors for the terminal
  output:
    ansi:
      enabled: ALWAYS

application:
  version: @project.version@